# Сообщение, которое выводится при использовании флая без элитр
notify-message: "&fТы не можешь летать без элитр!"
# Нужно ли проверять оп игроков
checkOp: false
# Нужно ли проверять игроков в креативе, не трогать
checkCreative: false
# Сколько прочности снимать
itemDurability: 1
# Как часто снимать прочность, в секундах
periodDurability: 3